#!/bin/bash


# scp -i ~/rpikey ./config/lobby-server.service vigo@192.168.178.172:/home/vigo/lobby-server.service 
# ssh -i ~/rpikey vigo@192.168.178.172 "sudo mv /home/vigo/lobby-server.service /lib/systemd/system/lobby-server.service"

GOOS=linux GOARCH=arm GOARM=7 go build .

ssh vigo@192.168.178.172 -i ~/rpikey "sudo systemctl stop lobby-server"

scp -i ~/rpikey ./lobby-server vigo@192.168.178.172:/home/vigo/lobby-server

ssh vigo@192.168.178.172 -i ~/rpikey "sudo systemctl start lobby-server"