/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpotifyCallbackImport } from './routes/spotify-callback'
import { Route as PlayImport } from './routes/play'
import { Route as HostImport } from './routes/host'
import { Route as IdImport } from './routes/$id'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SpotifyCallbackRoute = SpotifyCallbackImport.update({
  path: '/spotify-callback',
  getParentRoute: () => rootRoute,
} as any)

const PlayRoute = PlayImport.update({
  path: '/play',
  getParentRoute: () => rootRoute,
} as any)

const HostRoute = HostImport.update({
  path: '/host',
  getParentRoute: () => rootRoute,
} as any)

const IdRoute = IdImport.update({
  path: '/$id',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$id': {
      preLoaderRoute: typeof IdImport
      parentRoute: typeof rootRoute
    }
    '/host': {
      preLoaderRoute: typeof HostImport
      parentRoute: typeof rootRoute
    }
    '/play': {
      preLoaderRoute: typeof PlayImport
      parentRoute: typeof rootRoute
    }
    '/spotify-callback': {
      preLoaderRoute: typeof SpotifyCallbackImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  IdRoute,
  HostRoute,
  PlayRoute,
  SpotifyCallbackRoute,
])

/* prettier-ignore-end */
